version: '3.8'
services:
  client-dev:
    container_name: client-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./client-dev:/app
      - /app/node_modules
    env_file:
      - .env.local

  client-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '4000:4000'
    env_file:
      - .env.prod
